### ISSUE TITLE
Support for proxy when using PayPal EC

### ISSUE THREAD

**Issue by binarious** [Payum/PayumBundle#114]
I tried to set a custom buzz client (with a curl proxy) via:

```
payum:
    contexts:
       my_paypal_payment:
            paypal_express_checkout_nvp:
                api:
                    client: my.buzz.client
```

and the service defined like this:

```
my.buzz.client:
        class: Buzz\Client\Curl
        calls:
            - [setOption, [10004, "%proxy_host%:%proxy_port%"]]
```

`10004` is the constant `CURLOPT_PROXY`.

It works with a `NotifyRequest` (and it actually uses the proxy), but not when I try to capture a payment. Then I get the message `The TOKEN must be set. Have you executed SetExpressCheckoutAction?`. This worked without the custom buzz client. 

Any ideas?
