### ISSUE TITLE
 Unrecognized options "storages" under "payum.contexts.*** (0.9)

### ISSUE THREAD

**Issue by rogerb87** [Payum/PayumBundle#139]
Hey,

after upgrading Payum from 0.8 to 0.9 the parameters in the config.yml made easier. But I removed the api and option-option.

This is my config.yml:

``` yml
payum:
    security:
        token_storage:
            [...]\PaymentSecurityToken:
                doctrine:
                    driver: orm

    contexts:
        paypal_express:
            paypal_express_checkout_nvp:
                username:  '***'
                password:  '***'
                signature: '***'
                sandbox: true

            storages:
                [...]\PaymentDetails:
                    doctrine:
                        driver: orm
```

But when I do a composer update I got this error message:

> [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
>  Unrecognized options "storages" under "payum.contexts.paypal_express"  

For me it looks correct, just like here: 
http://payum.forma-dev.com/documentation/0.9/PayumBundle/simple_purchase_examples/paypal_express_checkout

Best regards,
Roger
