### ISSUE TITLE
 Unrecognized options "api" 

### ISSUE THREAD

**Issue by grekpg** [Payum/PayumBundle#158]
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized options "api" under "payum.contexts.f_payment.paypal_express_checkout_nvp"              

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception

config.yml

```
 contexts:
        f_payment:
            paypal_express_checkout_nvp:
              api:
                  options:
                      username:  %paypal.express_checkout.username%
                      password:  %paypal.express_checkout.password%
                      signature: %paypal.express_checkout.signature%
                      sandbox: %paypal.express_checkout.sandbox%
            storages:
                ed\partnerBundle\Entity\PaymentDetails:
                    doctrine:
                        driver: orm
```
