### ISSUE TITLE
... was not found in the chain configured namespaces Payum\Core\Model

### ISSUE THREAD

**Issue by Hetarnam** [Payum/PayumBundle#194]
Hi !
I try to install a Paypal express checkout this morning but that don't work...

I have this exception :
"The class 'Frontend\PaymentsBundle\Entity\PaymentDetails' was not found in the chain configured namespaces Payum\Core\Model"

My entity class : 

```
<?php
namespace Frontend\PaymentsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Payum\Core\Model\ArrayObject;

/**
 * @ORM\Table
 * @ORM\Entity
 */
class PaymentDetails extends ArrayObject
{
}
?>
```

My config :

```
orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                mappings:
                    payum:
                        is_bundle: false
                        type: xml
                        dir:     %kernel.root_dir%/../vendor/payum/core/Payum/Core/Bridge/Doctrine/Resources/mapping

                        prefix: Payum\Core\Model

payum:
    storages:
        Frontend\PaymentsBundle\Entity\PaymentDetails: {doctrine: orm}
    contexts:
        checkout_with_paypal:
            paypal_express_checkout_nvp:
                username:  '#'
                password:  '#'
                signature: '#'
                sandbox: false

    security:
        token_storage:
            Frontend\PaymentsBundle\Entity\SecurityToken: {doctrine: orm}
```

Have an idea? Please help !
