### ISSUE TITLE
Payum and Authorize.net

### ISSUE THREAD

**Issue by PedroTroller** [Payum/PayumBundle#199]
Hi everyone.

I try to use Payum with Authorize.Net and I think I've forgotten something.

So I've added some configuration...

``` yml
#config.yml
payum:
    #...
    contexts:
        authorize_net:
            authorize_net_aim:
                login_id: my_id
                transaction_key:  my_key
                sandbox: true
```

And I've got this error : 
![screenshot - 02122014 - 16 26 16](https://cloud.githubusercontent.com/assets/1766827/5265062/056b5ae4-7a40-11e4-8bb4-e7be850a0bd5.png)

I think I've forgotten something like actions registration... But I don't know what actions.

By the way, awesome work with Payum.

Thanks a lot.
