### ISSUE TITLE
How to disable Sonata as a backend 

### ISSUE THREAD

**Issue by jblanchon** [Payum/PayumBundle#255]
We don't want to use sonata as a backend, how to disable it, because we want to be able add paymentConfiguration in our own code. (without Sonata)

I tried :
```yml
    dynamic_payments:
        sonata_admin: false
        config_storage:
            Yprox\Model\GatewayConfig: { doctrine: orm }
```
I still get this error 
```
Attempted to load class "Admin" from namespace "Sonata\AdminBundle\Admin".
Did you forget a "use" statement for "Context\Page\Admin"?
```

thank you

PS : why did you choose to hardcode it with sonata when it's quite easy to do a simple form ?
