### ISSUE TITLE
Error with gateways configuration

### ISSUE THREAD

**Issue by silasrm** [Payum/PayumBundle#262]
Hi,

I'm trying to upgrade my version to 0.14.4 from 0.8.*, but this error happened:

```
 [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  Unrecognized option "gateways" under "payum"
```

I'm follow this example: https://github.com/makasim/PayumBundleSandbox/blob/master/app/config/payum.yml

My payum config:

```yaml
payum:
    security:
        token_storage:
            SON\BillingBundle\Entity\PayumSecurityToken:
                doctrine: orm

    storages:
        SON\BillingBundle\Entity\PaymentDetails:
            extension:
                all: true
            doctrine: orm
        SON\BillingBundle\Entity\AgreementDetails:
            extension:
                all: true
            doctrine: orm
        SON\BillingBundle\Entity\RecurringPaymentDetails:
            extension:
                all: true
            doctrine: orm

    gateways:
        paypal_express_checkout_and_doctrine_orm_with_ipn_enabled:
            paypal_express_checkout_nvp:
                username:  %paypal.express_checkout.username%
                password:  %paypal.express_checkout.password%
                signature: %paypal.express_checkout.signature%
                sandbox: %paypal.express_checkout.sandbox%

        paypal_express_checkout_and_doctrine_orm:
            paypal_express_checkout_nvp:
                username:  %paypal.express_checkout.username%
                password:  %paypal.express_checkout.password%
                signature: %paypal.express_checkout.signature%
                sandbox: %paypal.express_checkout.sandbox%

        paypal_express_checkout_recurring_payment_and_doctrine_orm:
            paypal_express_checkout_nvp:
                username:  %paypal.express_checkout.username%
                password:  %paypal.express_checkout.password%
                signature: %paypal.express_checkout.signature%
                sandbox: %paypal.express_checkout.sandbox%

        paypal_express_checkout_with_ipn_enabled:
            paypal_express_checkout_nvp:
                username:  %paypal.express_checkout.username%
                password:  %paypal.express_checkout.password%
                signature: %paypal.express_checkout.signature%
                sandbox: %paypal.express_checkout.sandbox%
                actions:
                    - son.billing.action.notification
```

How solve this error?
