### ISSUE TITLE
 The return_url must be set either to FormRequest or to options. 

### ISSUE THREAD

**Issue by Ziiweb** [Payum/PayumBundle#268]
Im getting this error: 

 The return_url must be set either to FormRequest or to options. 

How to solve it?

```
  public function prepareAction(Request $request)
  {

    $payment = new Payment;
    $payment->setNumber(uniqid());
    $payment->setCurrencyCode('EUR');
    $payment->setTotalAmount(123); // 1.23 EUR
    $payment->setDescription('A description');
    $payment->setClientId('anId');
    $payment->setClientEmail('foo@example.com');

    $gateway = $this->get('payum')->getGateway('paypal_express_checkout_and_doctrine_orm');
    $gateway->execute(new Capture($payment));
  }



    gateways:
        paypal_express_checkout_and_doctrine_orm:
            paypal_express_checkout_nvp:
                username: *******
                password: '********
                signature: ******
                sandbox: false
```

**Comment by makasim** [comment]
Could you post the whole payum configuration and the stacktrace of the exception.

**Comment by Ziiweb** [comment]
```
payum:
    security:
        token_storage:
            Project\BackendBundle\Entity\PaymentToken: { doctrine: orm }

    storages:
        Project\BackendBundle\Entity\Pedido: { doctrine: orm }

    gateways:
        paypal_express_checkout_and_doctrine_orm:
            paypal_express_checkout_nvp:
                username: 'Info_api1.mytravelbanners.com'
                password: 'HJ8TRM77XPBZNLZ7'
                signature: 'A2vpQOiJ4fpAlBiyO101LdkGCWzbAi5nmMzQWHXNdNKRRyRYpMHgEbQM'
                sandbox: false

```

I have these lines at my composer.json:

```
        "symfony/symfony": "2.5.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "dev-master",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0",
        "sensio/framework-extra-bundle": "~3.0",
        "incenteev/composer-parameter-handler": "~2.0",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "friendsofsymfony/elastica-bundle": "~3.0",
        "vich/uploader-bundle": "dev-master",
        "stof/doctrine-extensions-bundle": "~1.1@dev",
        "jquery/jquery":  "1.10.*",
        "jms/serializer-bundle": "~0.13",
        "knplabs/knp-gaufrette-bundle" : "@dev",
        "ext-curl": "*",
        "paypal/merchant-sdk-php": "*",
        "doctrine/migrations": "1.0.*@dev",
        "doctrine/doctrine-migrations-bundle": "2.1.*@dev",
        "payum/payum-bundle": "~0.14",
        "payum/paypal-express-checkout-nvp": "~0.14"

```
