### ISSUE TITLE
How to integrate PayumBundle + PayPal Rest

### ISSUE THREAD

**Issue by Emirii** [Payum/PayumBundle#292]
I saw that PayPal Rest API was one of the supported gateways, but it does not come with the Symfony2 Payum bundle.

I tried adding it to the composer payum/paypal-rest, then adding it in config, but it gives an error:

```
Fatal error: Uncaught exception 'Symfony\Component\Config\Definition\Exception\InvalidConfigurationException' with message 'Unrecognized option "paypal_rest" under "payum.gateways.my_paypal"' in /usr/share/nginx/html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php on line 309
```

Also, in Sonata admin, the gateways dropdown only says "Custom" and nothing else.

How can I integrate the PayPal Rest API into the Payum bundle? Thank you.

Here's my config:
```
payum:
    security:
        token_storage:
            Application\PaymentBundle\Entity\PaymentToken: { doctrine: orm }

    storages:
        Application\PaymentBundle\Entity\Payment: { doctrine: orm }
        
    dynamic_gateways:
        sonata_admin: true
        config_storage: 
            Application\PaymentBundle\Entity\GatewayConfig: { doctrine: orm } 

    gateways:
        paypal:
            paypal_rest:
                client_id: ~
                client_secret: ~
                config_path: ~
                sandbox: true
```
