### ISSUE TITLE
Custom guzzle client

### ISSUE THREAD

**Issue by lunetics** [Payum/PayumBundle#338]
For the Bundle, could we make the client configurable so it accepts a custom service (e.g. when using csa guzzle bundle, to have full debug / middleware capatibilities)

**Comment by makasim** [comment]
It is already possible, you have to overwrite this service https://github.com/Payum/PayumBundle/blob/master/Resources/config/payum.xml#L61

or (if you are on 2.x) 

```yaml
payum:
    gateways:
        foo:
            # ...
            payum.http_client: @the_http_client_service
```
