### ISSUE TITLE
Request Capture{model: PaymentDetails} is not supported.

### ISSUE THREAD

**Issue by rafikck** [Payum/PayumBundle#340]
Hi,
I have a problem with prepare paypal express checkout, During capturing payments I received exception:

_"Request Capture{model: PaymentDetails} is not supported. Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker."

**My controller code:**
...
$gatewayName = 'paypal_express_checkout_and_doctrine_orm';
 $storage = $this->get('payum')->getStorage('...\BackendBundle\Entity\PaymentDetails');

 $details = $storage->create();
        $details['PAYMENTREQUEST_0_CURRENCYCODE'] = "USD";
        $details['PAYMENTREQUEST_0_AMT'] = $dataCart['totalPrice'];
...

 $storage->update($details);

 $captureToken = $this->get('payum')->getTokenFactory()->createCaptureToken(
            $gatewayName, $details, 'payment_thankyoupage' // the route to redirect after capture;
        );
return $this->redirect($captureToken->getTargetUrl());

Someone could help me ?

**Comment by makasim** [comment]
Could you please post config.yml and payum and the bundle versions?

**Comment by rafikck** [comment]
config.yml:
...
```
payum:
    security:
        token_storage:
            ...\BackendBundle\Entity\PaymentToken: { doctrine: orm }

    storages:
        ...\BackendBundle\Entity\PaymentDetails: { doctrine: orm }

    gateways:
        offline:
            offline: ~

        paypal_express_checkout_and_doctrine_orm:
            paypal_express_checkout_nvp:
                username:  "xxx"
                password:  "xxx"
                signature: "xxx"
                sandbox: false
        authorize_net_checkout_and_doctrine_orm:
            authorize_net_aim:
                login_id: 'xxx'
                transaction_key: 'xxx'
                sandbox: false
```


composer file:
...
```
        "payum/payum-bundle": "dev-master",
        "payum/offline": "dev-master",
        "payum/paypal-express-checkout-nvp": "dev-master",
        "payum/authorize-net-aim": "dev-master",
```
