### ISSUE TITLE
Best way to add a different flow

### ISSUE THREAD

**Issue by lunetics** [Payum/PayumBundle#342]
What would be the best or preferred flow when I want stripe have another logic.

e.g. i want to create a customer first and later have the cust_*** token instead of the card token.

1) Is there anyway to configure it, so I could push it upstream? The StripeCheckoutGatewayFactory has config defaults, that needs to be different (e.g. CreateCustomerAction before charge, another CreateToCustomerChargeAction with different logic)

Same with (still in beta) stripe direct debit / SEPA.

2) would be clone into e.g. stripe-customer or stripe-direct debit and include that into Payum (code smell, since only 2 or 3 action changes?)

**Comment by lunetics** [comment]
Okay, I went the way like stripe_js extends stripe_checkout with one added action. But it seems on this the extensions and storages are not added (only the default EndlessCycleDetectorExtension from the Core)

Could not find out yet why the default extension (which are tagged with all=true by default) are not added to this gateway. Maybe some wrong order?

console output for payum:gateway:debug:

```
stripe_js (Payum\Core\Gateway):
	Actions:
	Payum\Core\Bridge\PlainPhp\Action\GetHttpRequestAction
	Payum\Core\Action\CapturePaymentAction
	Payum\Core\Action\ExecuteSameRequestWithModelDetailsAction
	Payum\Core\Bridge\Twig\Action\RenderTemplateAction
	Payum\Core\Action\GetCurrencyAction
	Payum\Core\Action\GetTokenAction
	Payum\Stripe\Action\CaptureAction
	Payum\Stripe\Action\ConvertPaymentAction
	Payum\Stripe\Action\StatusAction
	Payum\Stripe\Action\Api\ObtainTokenAction
	Payum\Stripe\Action\Api\CreateChargeAction

	Extensions:
	Payum\Core\Extension\GenericTokenFactoryExtension
	Payum\Core\Bridge\Psr\Log\LoggerExtension
	Payum\Core\Bridge\Psr\Log\LogExecutedActionsExtension
	Payum\Core\Extension\StorageExtension
		Storage: Payum\Core\Bridge\Doctrine\Storage\DoctrineStorage
		Model: AppBundle\Entity\Billing\Payment
	Payum\Core\Extension\EndlessCycleDetectorExtension

	Apis:
	Payum\Core\Bridge\Guzzle\HttpClient
	Payum\Stripe\Keys

stripe_js_customer (Payum\Core\Gateway):
	Actions:
	Payum\Core\Bridge\PlainPhp\Action\GetHttpRequestAction
	Payum\Core\Action\CapturePaymentAction
	Payum\Core\Action\ExecuteSameRequestWithModelDetailsAction
	Payum\Core\Bridge\Twig\Action\RenderTemplateAction
	Payum\Core\Action\GetCurrencyAction
	AppBundle\Services\Payum\Stripe\Action\Api\CreateCustomerAction
	Payum\Stripe\Action\CaptureAction
	Payum\Stripe\Action\ConvertPaymentAction
	Payum\Stripe\Action\StatusAction
	Payum\Stripe\Action\Api\ObtainTokenAction
	Payum\Stripe\Action\Api\CreateChargeAction

	Extensions:
	Payum\Core\Extension\EndlessCycleDetectorExtension

	Apis:
	Payum\Core\Bridge\Guzzle\HttpClient
	Payum\Stripe\Keys
```

config:
```yaml
payum:
    security:
        token_storage:
            AppBundle\Entity\Billing\PaymentToken: { doctrine: orm }

    storages:
        AppBundle\Entity\Billing\Payment:
            doctrine: orm

    gateways:
        offline:
            factory: offline

        stripe_js:
            factory: stripe_js
            publishable_key: %api.payum.gateway.stripe.publishable_key%
            secret_key: %api.payum.gateway.stripe.secret_key%

        stripe_js_customer:
            factory: stripe_js_customer
            publishable_key: %api.payum.gateway.stripe.publishable_key%
            secret_key: %api.payum.gateway.stripe.secret_key%
```

factory config:
```xml
...
       <service id="app.payum.stripe.gateway.stripe_js_customer" class="AppBundle\Services\Payum\Stripe\StripeCustomerCheckoutGatewayFactory" >
            <tag name="payum.gateway_factory" factory="stripe_js_customer"  />
        </service>
...
```

StripeCustomerCheckoutGatewayFactory:

```php
<?php
namespace AppBundle\Services\Payum\Stripe;

use AppBundle\Services\Payum\Stripe\Action\Api\CreateCustomerAction;
use Payum\Core\Bridge\Spl\ArrayObject;
use Payum\Stripe\Action\Api\CreateChargeAction;
use Payum\Stripe\Action\Api\ObtainTokenAction;
use Payum\Stripe\Action\CaptureAction;
use Payum\Stripe\Action\ConvertPaymentAction;
use Payum\Stripe\Action\StatusAction;
use Payum\Stripe\StripeCheckoutGatewayFactory;

class StripeCustomerCheckoutGatewayFactory extends StripeCheckoutGatewayFactory
{
    /**
     * {@inheritDoc}
     */
    protected function populateConfig(ArrayObject $config)
    {
        if (!class_exists('\Stripe\Stripe')) {
            throw new \LogicException('You must install "stripe/stripe-php:~2.0|~3.0" library.');
        }

        $config->defaults(array(
            'payum.factory_name' => 'stripe_js_customer',
            'payum.factory_title' => 'Stripe.Js with Customer creation',

            'payum.template.obtain_token' => '@PayumStripe/Action/obtain_js_token.html.twig',

            'payum.action.create_customer' => new CreateCustomerAction(),
            'payum.action.capture' => new CaptureAction(),
            'payum.action.convert_payment' => new ConvertPaymentAction(),
            'payum.action.status' => new StatusAction(),
            'payum.action.obtain_token' => function (ArrayObject $config) {
                return new ObtainTokenAction($config['payum.template.obtain_token']);
            },
            'payum.action.create_charge' => new CreateChargeAction(),
        ));
        
        parent::populateConfig($config);
    }
}
```

**Comment by makasim** [comment]
you have to use `payum.gateway_factory_builder` tag in order to be have extensions registered. The service has to be an instance of https://github.com/Payum/Payum/blob/master/src/Payum/Core/Bridge/Symfony/Builder/GatewayFactoryBuilder.php

**Comment by makasim** [comment]
By the way you can overwrite the services without a factory, like this:

```
payum:
    gateways:
        stripe:
            factory: stripe_checkout
            payum.action.capture: @app.payum.stripe.capture_action
```

same if you want to add an extra services. you can do it with container tags too.
