### ISSUE TITLE
Issue with the gateway factory "paypal_express_checkout" 

### ISSUE THREAD

**Issue by n1c01a5** [Payum/PayumBundle#369]
Hi,

I have this error : 
```
Gateway factory "paypal_express_checkout" does not exist. 
```

My configuration (config.yml): 
```
payum:
    security:
        token_storage:
            Application\PaymentBundle\Entity\PaymentToken: { doctrine: orm }

    storages:
        Application\PaymentBundle\Entity\PaymentDetails: { doctrine: orm }

    gateways:
        paypal_express_checkout_and_doctrine_orm:
            factory: paypal_express_checkout
            username:  'id'
            password:  'pass'
            signature: 'sign'
            sandbox: true
```

Thanks for your help
