### ISSUE TITLE
Gateway config must have factory set in it and it must not be empty

### ISSUE THREAD

**Issue by Tomenbois** [Payum/PayumBundle#373]
Hi,
i have this error

> Gateway config must have factory set in it and it must not be empty.

My configuration (config.yml): 

```
payum:
    security:
        token_storage:
            PaymentBundle\Entity\PaymentToken: { doctrine: orm }
    storages:
        PaymentBundle\Entity\PaymentDetails: { doctrine: orm }
    gateways:
        offline:
            offline: ~
        stripe:
            stripe_js:
                factory: stripe_js
                publishable_key: 'xxx'
                secret_key:      'yyy'   
        paypal:
            paypal_express_checkout_nvp:
                factory: paypal_express_checkout
                username: 'xxx'
                password: 'yyy'
                signature: 'zzz'
                sandbox: false
```
and my composer.json

```
"payum/payum-bundle": "^2.0",
"payum/offline": "^1.1",
"payum/paypal-express-checkout-nvp": "^1.3",
"payum/core": "^1.3",
"payum/stripe": "dev-master",
```

Thanks for your help

**Comment by makasim** [comment]
It must be like this:

```yaml
gateways:
        offline:
            factory: offline
        stripe:
                factory: stripe_js
                publishable_key: 'xxx'
                secret_key:      'yyy'   
        paypal:
                factory: paypal_express_checkout
                username: 'xxx'
                password: 'yyy'
                signature: 'zzz'
                sandbox: false
```
