### ISSUE TITLE
Unable to generate a URL for the named route "payum_notify_do" as such route does not exist

### ISSUE THREAD

**Issue by napestershine** [Payum/PayumBundle#374]
HI

I am getting following error when using paypal express checkout:
Unable to generate a URL for the named route "payum_notify_do" as such route does not exist

Any solution?
Thanks

**Comment by makasim** [comment]
You did not import such routes, 

```yaml
# app/config/routing.yml

payum_capture:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"
```
