### ISSUE TITLE
Can't get it to work in sandbox

### ISSUE THREAD

**Issue by dijadev** [Payum/PayumBundle#395]
Hi everyone,
I am trying to integrate this bundle using Express Checkout gateway..
But can't get it to work in sandbox..it returns "Security header is not valid" as a response message.

When I turn sandbox conf to false it works ;
```
 paypal_express_checkout:
            factory: paypal_express_checkout
            username: %paypal_checkout_username%
            password: %paypal_checkout_password%
            signature: %paypal_checkout_signature%
            sandbox: false
```
Tanks for your help in advance,
