### ISSUE TITLE
Can't add new custom gateway. InvalidConfigurationException in ArrayNode.php 

### ISSUE THREAD

**Issue by diimpp** [Payum/PayumBundle#396]
Hello @makasim,

I'm getting this error
```
InvalidConfigurationException in ArrayNode.php line 312: Unrecognized option "acme" under "payum.gateways.acme"
```
I've read like whole bugtracker and number of SO questions, but still stuck.

I've sylius 0.16 instance with payum and payum-bundle 1.0 and trying to register non-standard gateway.
Configuration is sylius standard payum configuration plus my `acme` gateway, which looks like that
```yaml
 payum:
     storages:
         Acme\Bundle\CoreBundle\Entity\Order: { doctrine: orm }
         Acme\Bundle\CoreBundle\Entity\Payment: { doctrine: orm }
 
     security:
         token_storage:
             Sylius\Bundle\PayumBundle\Model\PaymentSecurityToken: { doctrine: orm }
 
     dynamic_gateways:
         config_storage:
             Sylius\Bundle\PayumBundle\Model\GatewayConfig: { doctrine: orm }
 
     gateways:
         acme:
             acme:
                 factory: acme
                 password:  %acme.password%
                 sandbox:   %acme.sandbox%
         paypal_express_checkout:
             paypal_express_checkout_nvp:
                 username:  %paypal.express_checkout.username%
                 password:  %paypal.express_checkout.password%
                 signature: %paypal.express_checkout.signature%
                 sandbox:   %paypal.express_checkout.sandbox%
 
         be2bill_direct:
             be2bill_direct:
                 identifier: %be2bill.identifier%
                 password:   %be2bill.password%
                 sandbox:    %be2bill.sandbox%
 
         be2bill_offsite:
             be2bill_offsite:
                 identifier: %be2bill.identifier%
                 password:   %be2bill.password%
                 sandbox:    %be2bill.sandbox%
 
         stripe_checkout:
             stripe_checkout:
                 publishable_key: %stripe.publishable_key%
                 secret_key: %stripe.secret_key%
 
         offline:
             offline: ~
```

Service for my acme factory
```yaml
     app.payum.acme.gateway_factory_builder:
         class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
         arguments:
             - App\Payum\Acme\AcmeGatewayFactory
         tags:
             - { name: payum.gateway_factory_builder factory: acme }
```
which seems correct by your answer in different issue https://github.com/Payum/PayumBundle/issues/342#issuecomment-188777542 and for example by readme for https://github.com/BoShurik/payum-yandex-money

I'm out of options for what to try next to fix this. Can you please suggest which way I need to take.

Thank you for any information.

**Comment by makasim** [comment]
It must be like that:

```yaml
gateways:
         acme:
                 factory: acme
                 password:  %acme.password%
                 sandbox:   %acme.sandbox%
```

The config you posted is for previous versions 1.x.
