### ISSUE TITLE
No Extensions in tagged gateway factories

### ISSUE THREAD

**Issue by toooni** [Payum/PayumBundle#397]
Hi @makasim 

I am trying to implement another gateway with the `payum.gateway_factory` tag. The factory is working but unfortunately there is only one extension "assigned" to the gateways of the factory. 

![image](https://cloud.githubusercontent.com/assets/241080/19015682/1af75218-8809-11e6-9899-3859e5391211.png)

This is the gateway factory service definition:
```
  payum.postfinance_direct_link_gateway_factory:
      class: Payum\PostfinanceDirectLink\PostfinanceDirectLinkGatewayFactory
      tags:
          - { name: payum.gateway_factory, factory: postfinance_direct_link }
```

Every other gateway (bundled with payum) does have the extensions needed. I am using the following config for an extension (already in productive use):

```
  payum.extension.payment_status:
    class: Invit\PaymentBundle\Payum\PaymentStatusExtension
    arguments:
      - '@payum.storage.weekend4two_backendbundle_entity_payment'
    tags:
        - { name: payum.extension, all: true }
```

Do you have an idea what I might be doing wrong?

Best regards
Toni
