### ISSUE TITLE
Omnipay Mollie gateway problem 

### ISSUE THREAD

**Issue by kurakin-oleksandr** [Payum/PayumBundle#403]
I get an error `RequestNotSupportedException`: "Request Convert is not supported. Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker."

config.yml
```
payum:
  gateways:
    ideal:
      type: "Mollie"
      apiKey: 'my_test_api_key'
      factory: "omnipay_mollie"
```

What can be a problem?
