### ISSUE TITLE
Gateway containing other payment methods question

### ISSUE THREAD

**Issue by webmake** [Payum/PayumBundle#436]
Hello,

I didn't find any solution, how like simmilar ones `$this->get('payum')->getGateways()` and `$this->get('payum')->getGatewayFactories()` to get one gateways' other containing methods. I think most similar example would be `buildOmnipayGatewayFactories`, but I cannot declare as gatewayFactory not existing factories, because only core can do this, so I achieved payment creation itself with configs, during convert action resolving actual payment, example of such config:
```
payum:
    gateways:
        paypal_pro:
            factory: omnipay
            type: PayPal_Express
            testMode: true
        my_payment:
            factory: my_payment
            payment_methods:
                visa:
                    payment_method: visa
                    type: card
                maestro:
                    payment_method: maestro
                    type: card
```
But I cannot access those configured payment_methods via `$this->get('payum')->getGateway('my_payment')` somehow, because it's returning object is `Payum\Core\Gateway`, so I am feeling, that I'm doing something wrongly.

So questions are: is it possible via payum itself return according gateway its belonging payment methods?

Is it any possibility to build factories like omnipay, without touching the core? I can't remember exactly what issue I had, but after some debugging I decided to do customized configs like in example above, (I hardly remember that I had a problem that those registered gateways didn't exist, so didn't succeeded to create payment at all)
