### ISSUE TITLE
Issue with payum.template.obtain_token template overriding

### ISSUE THREAD

**Issue by 41man** [Payum/PayumBundle#457]
Trying to override payum.template.obtain_token template value and use own template but get error:
"Template "@PaymentBundle/Action/obtain_js_token.html.twig" is not defined.
500 Internal Server Error - Twig_Error_Loader "
Config.yml:

```yaml
payum:
  gateways:
    audio_stripe_checkout:
      payum.template.obtain_token: '@PaymentBundle/Action/obtain_js_token.html.twig'
```

I tried to set different values and got same error. Please help.

composer values:
```
"payum/core": "^1.4.1",
"payum/payum": "^2.0",
 "payum/payum-bundle": "2.0.0",
```
