### ISSUE TITLE
Request Authorize{model: string} is not supported

### ISSUE THREAD

**Issue by kubaceg** [Payum/PayumBundle#460]
I have problem with payum bundle and paypal_express_checkout in sf4. When I try to authorize payment I get:
`Request Authorize{model: string} is not supported. Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker.`

Maybe someone can help me, I try to debug this but after few hours I have no idea what's wrong.

Here are my config files:
payum.yml
```
payum:
    security:
        token_storage:
            App\Entity\Payment\PaymentToken: { doctrine: orm }

    storages:
        App\Entity\Payment\Payment: { doctrine: orm }

    gateways:
        paypal:
            factory: paypal_express_checkout
            username: fdfd
            password:  'fdfd'
            signature: 'fdfd'
            sandbox: true
```
Entity\Payment\Payment:
```
<?php

namespace App\Entity\Payment;

use Payum\Core\Model\Payment as BasePayment;

class Payment extends BasePayment
{
    protected $id;
}
```
Entity\Payment\PaymentToken:
```
<?php

namespace App\Entity\Payment;

use Payum\Core\Model\Token;

class PaymentToken extends Token
{
}
```
And I move mapping into yaml:
```
App\Entity\Payment\Payment:
    type: entity
    id:
        id:
            type: integer
            generator: {strategy: AUTO}

    fields:

        number:
            type: string
            nullable: true

        description:
            type: string
            nullable: true

        clientEmail:
            type: string
            nullable: true

        clientId:
            type: string
            nullable: true

        totalAmount:
            type: integer
            nullable: true

        currencyCode:
            type: string
            nullable: true

        details:
            type: json_array
            nullable: true
```
```
App\Entity\Payment\PaymentToken:
    type: entity
    id:
        hash:
            type: string
            generator: {strategy: NONE}

    fields:

        details:
            type: string
            nullable: true

        afterUrl:
            type: string
            nullable: true

        targetUrl:
            type: string
            nullable: false

        gatewayName:
            type: string
            nullable: false
```
Authorize initialization
```
        $gatewayName = 'paypal';

        /** @var StorageInterface $storage */
        $storage = $this->get('payum')->getStorage(Payment::class);

        $payment = $storage->create();
        $payment->setNumber(uniqid());
        $payment->setCurrencyCode('EUR');
        $payment->setTotalAmount(123);
        $payment->setDescription('A description');
        $payment->setClientId('anId');
        $payment->setClientEmail('foo@example.com');

        $storage->update($payment);

        /** @var TokenInterface $captureToken */
        $captureToken = $this->get('payum')->getTokenFactory()->createAuthorizeToken(
            $gatewayName,
            $payment,
            'success'
        );

        return $this->redirect($captureToken->getTargetUrl());
```
