### ISSUE TITLE
In symfony 4 it's not possible to pass service through gateway configuration

### ISSUE THREAD

**Issue by Tetragramat** [Payum/PayumBundle#497]
Example configuration
```yaml
payum:
    gateways:
        foo_gateway:
            factory: foo_gateway
            some_service: "@app.some_service"
```
Result in symfony 4 (tested on 4.2 and 4.3)
```php
// FooGatewayFactory.php
dump($config['some_service']); // returns: string "@app.some_service"
```
Result in symfony 3.4
```php
// FooGatewayFactory.php
dump($config['some_service']); // returns: instance of SomeService
```

This means that part of the documentation of payum does not work because it depends on being able to pass service through configuration.
