### ISSUE TITLE
Controllers do not work in Symfony 5.0.4

### ISSUE THREAD

**Issue by AlexeyKosov** [Payum/PayumBundle#507]
The abstract PayumController uses `$this->get('payum')` for accessing the service, but this way no longer works and throws an exception in Symfony 5.0.4:

> Service "payum" not found: even though it exists in the app's container, the container inside "Payum\Bundle\PayumBundle\Controller\CaptureController" is a smaller service locator that only knows about the "doctrine", "form.factory", "http_kernel", "parameter_bag", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "serializer", "session" and "twig" services. 
> Try using dependency injection instead.

Obviously, `$this->get()` should be replaced with dependency injection through a constructor.

**Comment by Tetragramat** [comment]
When I'll find time I'll fix the issue. In the meantime you can solve this issue by adding something like this into your services.yaml
```yaml
# config/services.yaml
services:
    Payum\Bundle\PayumBundle\Controller\AuthorizeController:
        calls:
            - method: setContainer
              arguments: ['@service_container']

    Payum\Bundle\PayumBundle\Controller\CancelController:
        calls:
            - method: setContainer
              arguments: ['@service_container']

    Payum\Bundle\PayumBundle\Controller\CaptureController:
        calls:
            - method: setContainer
              arguments: ['@service_container']

    Payum\Bundle\PayumBundle\Controller\NotifyController:
        calls:
            - method: setContainer
              arguments: ['@service_container']

    Payum\Bundle\PayumBundle\Controller\PayoutController:
        calls:
            - method: setContainer
              arguments: ['@service_container']

    Payum\Bundle\PayumBundle\Controller\RefundController:
        calls:
            - method: setContainer
              arguments: ['@service_container']

    Payum\Bundle\PayumBundle\Controller\SyncController:
        calls:
            - method: setContainer
              arguments: ['@service_container']
```
