### ISSUE TITLE
Class 'Payum\Bridge\Doctrine\Entity\Token' not found

### ISSUE THREAD

**Issue by eloygonzalez** [Payum/PayumBundle#76]
Hello
I am setting "payum / payum-bundle": "dev-master" but I get an error.

 Class 'Payum\Bridge\Doctrine\Entity\Token' not found in /home/eloy/www/proditive/src/Eloryan/TiendaBundle/Entity/PayumSecurityToken.php on line 13

I do not know what I do wrong

Thanks
Sorry for  my english

```
namespace Eloryan\TiendaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Payum\Bridge\Doctrine\Entity\Token;


/**
 * @ORM\Table(name="payum_security_token")
 * @ORM\Entity
 */
class PayumSecurityToken extends Token
{

}
```

My settings

```
#payum.yml
doctrine:
   orm:
      entity_managers:
          default:
            mappings:
              payum:
                is_bundle: false
                type: xml
                dir: "%kernel.root_dir%/../vendor/payum/payum/src/Payum/Bridge/Doctrine/Resources/mapping"
                prefix: Payum\Bridge\Doctrine\Entity

payum:
    security:
        token_storage:
            Eloryan\TiendaBundle\Entity\PayumSecurityToken:
                doctrine:
                    driver: orm
```
