### ISSUE TITLE
Request BinaryMaskStatusRequest{model: PaymentProfile} is not supported. 

### ISSUE THREAD

**Issue by weburnit** [Payum/PayumBundle#92]
I dont know why this issue comes with me.
Here is my config 

``` yml

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

        mappings:
            payum:
                is_bundle: false
                type: xml
                dir: %kernel.root_dir%/../vendor/payum/core/Payum/Core/Bridge/Doctrine/Resources/mapping
                prefix: Payum\Core\Model

payum:
    contexts:
        paypalexpress:
            paypal_express_checkout_nvp:
                api:
                    options:
                        username:  'xxx'
                        password:  'wwww'
                        signature: 'xxxx'
                        sandbox: true
            storages:
                Gpl\GplBundle\Entity\PaymentProfile:
                    doctrine:
                        driver: orm
                        payment_extension: true
        stripe:
            omnipay:
                type: Stripe
                options:
                    apiKey: xxxxx
                    testMode: true
            storages:
                Gpl\GplBundle\Entity\PaymentProfile:
                    doctrine:
                        driver: orm
                        payment_extension: true
    security:
        token_storage:
            Gpl\GplBundle\Entity\PaymentToken:
                doctrine:
                    driver: orm
```

There is also one weird issue during my debug process in file: Payum/Core/Payment.php at line  97

``` php
// If i use var_dump right here: var_dump( $this->findActionSupported($request));
// it returns an Action Object
            if (false == $action = $this->findActionSupported($request)) {// if leave the original code, it always false right here.
                throw RequestNotSupportedException::create($request);
            }

            $this->extensions->onExecute($request, $action);
```

Any replies are thanks in advanced.

Regards.
